### PR TITLE
Create config.yml

### PR DESCRIPTION
**Pull request by UnknownBoy-sys**

### CODE REVIEW

**Comment by Prashant-1695** [comment]
@UnknownBoy-sys Wtf

**Comment by ImSpiDy** [comment]
@UnknownBoy-sys Nice lmao

**Comment by ImSpiDy** [comment]
@Prashant-1695 Bhaiya kya kar rhe

**Comment by ImSpiDy** [comment]
@UnknownBoy-sys Wow bhaiya

**Comment by ImSpiDy** [comment]
@ImSpiDy Ok

**Comment by reaPeR1010** [comment]
@Prashant-1695 Ok gay back

**Comment by reaPeR1010** [comment]
@reaPeR1010 Bhag bsdi

**Comment by reaPeR1010** [comment]
@reaPeR1010 Maderchod

**Comment by reaPeR1010** [comment]
@reaPeR1010 Randi

**Comment by reaPeR1010** [comment]
@reaPeR1010 @akirasupr join bish
Let's pawri

**Comment by reaPeR1010** [comment]
@reaPeR1010 Spidy is Gay AF

**Comment by reaPeR1010** [comment]
@reaPeR1010 ProShant is now GayShant

**Comment by reaPeR1010** [comment]
@reaPeR1010 Wen 66Hz

**Comment by UnknownBoy-sys** [comment]
@reaPeR1010

**Comment by reaPeR1010** [comment]
@UnknownBoy-sys Yea boii

**Comment by reaPeR1010** [comment]
@reaPeR1010 @NotZeetaa @SpiDyX027 contribute wen

**Comment by reaPeR1010** [comment]
@reaPeR1010 Tag here bsdi

**Comment by ImSpiDy** [comment]
@reaPeR1010 Lmao

**Comment by reaPeR1010** [comment]
@ImSpiDy Spidy machar ki jaat

**Comment by ImSpiDy** [comment]
@reaPeR1010 @reaPeR_1010 machar ki jaat ka baal

**Comment by reaPeR1010** [comment]
@ImSpiDy ChutiyAkira ka lund

**Comment by ImSpiDy** [comment]
@reaPeR1010 Akira Riya Ka pati

**Comment by Botvaibhav** [comment]
Bhen ke laddoo

**Comment by reaPeR1010** [comment]
@ImSpiDy SpiGay ProShant ka chut

**Comment by ImSpiDy** [comment]
@Botvaibhav Chup matherboard

**Comment by ImSpiDy** [comment]
@reaPeR1010 Chup riya ramdi

**Comment by reaPeR1010** [comment]
@ImSpiDy Bhag bsdk
Gand marunga

**Comment by Botvaibhav** [comment]
Bc delete kider hota hai behnchodai

**Comment by ImSpiDy** [comment]
@Botvaibhav Chup lavdu

**Comment by ImSpiDy** [comment]
@Botvaibhav Riya ke g se

**Comment by reaPeR1010** [comment]
@ImSpiDy SpiGay ka 2cm wala Lund

**Comment by ImSpiDy** [comment]
@reaPeR1010 Wo Akira ka hai

**Comment by shubhamxdd** [comment]
@ImSpiDy Nice spam

**Comment by NotZeetaa** [comment]
> @reaPeR1010 @NotZeetaa @SpiDyX027 contribute wen

Bish

**Pull request closed without merging**
